version: "3.8"
services:
  web:
    container_name: punto_venta
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app