###
POST http://localhost:3000/crearProducto HTTP/1.1
Content-Type:  application/json

{
    "nombre": "chicle",
    "tipo": "dulces",
    "precio": 2
}

###
GET http://localhost:3000/obtenerProducto/64b80e5565f53f229ea0517d HTTP/1.1

###
GET http://localhost:3000/obtenerProductos HTTP/1.1

###
PUT http://localhost:3000/updateProducto/64b80e5565f53f229ea0517d HTTP/1.1
Content-Type:  application/json

{
    "nombre": "Sprite 1.5L",
    "tipo": "bebidas",
    "precio": 23
}

###
DELETE http://localhost:3000/eliminarProducto/64b8119104655604a09dd675 HTTP/1.1

###
GET http://localhost:3000/obtenerProductosByNombreProducto/Coca cola HTTP/1.1