###
POST  http://localhost:3000/crearIngreso HTTP/1.1
Content-Type: application/json

{
    "cantidad": 6000
}

###
GET http://localhost:3000/obtenerIngresos HTTP/1.1

###
GET http://localhost:3000/obtenerIngreso/64c1806f30717a340e73705f HTTP/1.1

###
PUT http://localhost:3000/actualizarIngreso/64c1806f30717a340e73705f HTTP/1.1
Content-Type: application/json

{
    "cantidad": 4000
}

###
DELETE http://localhost:3000/eliminarIngreso/64c184a0bac168790d56dc16 HTTP/1.1